### ISSUE TITLE
Cant view options of Module

### ISSUE THREAD

**Issue by sistemasazulana** [compropago/plugin-opencart#3]
i can´t configure any option of the plugin

Fatal error: Can't use method return value in write context in /home/xxxxxxx/public_html/admin/controller/payment/compropago.php on line 198

i´m using the 2.2 version of opencart

**Comment by danteay** [comment]
What's the version of the ComproPago plugin that is installed in your site??

**Comment by sistemasazulana** [comment]
2.1.0 AND 2.1.1

**Comment by danteay** [comment]
Hellow.

This error apears beacause your PHP version is below 5.5, please check your PHP version and updateit.

**Comment by sistemasazulana** [comment]
thank you so much, that solve the issue
